name: flutternewcovid
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  backdrop: ^0.2.14
  http: ^0.12.1
  geolocator: ^5.3.1
  geocoder: ^0.2.1
  flutter_spinkit: ^4.1.2+1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/android_singh.PNG

  fonts:
  - family: Girassol
    fonts:
    - asset: fonts/Girassol-Regular.ttf

  - family: LexendGiga
    fonts:
    - asset: fonts/LexendGiga-Regular.ttf
